import type { RubricCriterion } from "@/lib/eng/authoring/package";
import { AUTHORED_STATE_LABEL, type EmployerAuthoredEvaluation } from "./types";

/**
 * Interview follow-ups and a decision brief for an employer-authored work
 * sample. Built only from the evaluation and the rubric: every question names
 * the finding it comes from, and nothing is generated by a model.
 */

export interface AuthoredFollowUp {
  criterionId: string;
  criterionLabel: string;
  /** Why this question is suggested, in terms of the evaluation. */
  basis: string;
  question: string;
  /** Test names behind the finding. Protected names are for the employer only. */
  tests: string[];
}

export interface AuthoredDecisionBrief {
  acceptance: { confirmed: number; notConfirmed: number; noResult: number; total: number };
  demonstrated: string[];
  partial: string[];
  concerns: string[];
  notAssessed: string[];
  limitations: string[];
}

const MAX_TESTS = 3;

function failingTests(evaluation: EmployerAuthoredEvaluation, acceptanceIds: string[]): string[] {
  const ids = new Set(acceptanceIds);
  return evaluation.tests
    .filter((t) => t.outcome !== "passed" && t.outcome !== "skipped" && t.criterionIds.some((id) => ids.has(id)))
    .map((t) => t.name)
    .slice(0, MAX_TESTS);
}

function unconfirmedAcceptance(evaluation: EmployerAuthoredEvaluation, acceptanceIds: string[]) {
  const ids = new Set(acceptanceIds);
  return evaluation.acceptance.filter((a) => ids.has(a.id) && a.state !== "confirmed");
}

function sentence(text: string): string {
  const t = text.trim();
  return /[.?!]$/.test(t) ? t : `${t}.`;
}

export function buildAuthoredFollowUps(evaluation: EmployerAuthoredEvaluation, rubric: RubricCriterion[]): AuthoredFollowUp[] {
  const byId = new Map(rubric.map((r) => [r.id, r]));
  const out: AuthoredFollowUp[] = [];
  for (const c of evaluation.criteria) {
    const r = byId.get(c.id);
    if (c.judgedBy === "reviewer") {
      out.push({
        criterionId: c.id,
        criterionLabel: c.label,
        basis: "Tests do not judge this criterion. It is left for your review.",
        question: r?.observableEvidence
          ? `Ask the candidate to point to where their work shows this: ${sentence(r.observableEvidence)}`
          : `Ask the candidate how their work addresses ${c.label.toLowerCase()}.`,
        tests: [],
      });
      continue;
    }
    if (c.state === "demonstrated" || c.state === "not_assessed") continue;
    const open = unconfirmedAcceptance(evaluation, c.acceptanceCriterionIds);
    const tests = failingTests(evaluation, c.acceptanceCriterionIds);
    if (c.state === "insufficient_evidence") {
      out.push({
        criterionId: c.id,
        criterionLabel: c.label,
        basis: `${AUTHORED_STATE_LABEL[c.state]}: the tests for ${c.acceptanceCriterionIds.join(", ") || "this criterion"} did not produce a result.`,
        question: open[0]
          ? `Ask how their change handles this requirement and how they checked it: ${sentence(open[0].text)}`
          : `Ask how they checked ${c.label.toLowerCase()} in their change.`,
        tests,
      });
      continue;
    }
    for (const a of open.slice(0, 2)) {
      const failed = failingTests(evaluation, [a.id]);
      out.push({
        criterionId: c.id,
        criterionLabel: c.label,
        basis: `${AUTHORED_STATE_LABEL[c.state]}: ${a.id} was not confirmed${failed.length ? `; ${failed.length === 1 ? "this test" : "these tests"} did not pass` : ""}.`,
        question: `Ask the candidate to walk through what their change does for this requirement, and what they would change: ${sentence(a.text)}`,
        tests: failed,
      });
    }
  }
  return out;
}

export function buildAuthoredDecisionBrief(evaluation: EmployerAuthoredEvaluation): AuthoredDecisionBrief {
  const acc = evaluation.acceptance;
  const label = (state: string) => evaluation.criteria.filter((c) => c.judgedBy === "tests" && c.state === state).map((c) => c.label);
  return {
    acceptance: {
      confirmed: acc.filter((a) => a.state === "confirmed").length,
      notConfirmed: acc.filter((a) => a.state === "not_confirmed").length,
      noResult: acc.filter((a) => a.state === "no_result").length,
      total: acc.length,
    },
    demonstrated: label("demonstrated"),
    partial: label("partially_demonstrated"),
    concerns: label("concern_observed"),
    notAssessed: evaluation.criteria
      .filter((c) => c.judgedBy === "reviewer" || c.state === "not_assessed" || c.state === "insufficient_evidence")
      .map((c) => c.label),
    limitations: evaluation.limitations,
  };
}

export interface SubmissionChanges {
  /** Starter files the candidate changed. */
  changed: string[];
  /** Files the candidate added that the starter did not have. */
  added: string[];
}

function listPaths(paths: string[], max = 3): string {
  const shown = paths.slice(0, max);
  const rest = paths.length - shown.length;
  const text = shown.length <= 1 ? shown.join("") : `${shown.slice(0, -1).join(", ")} and ${shown[shown.length - 1]}`;
  return rest > 0 ? `${text} and ${rest} more` : text;
}

/** A criterion is quoted whole: cutting it mid-sentence drops what it requires. */
function criterionText(text: string): string {
  return text.trim().replace(/\.$/, "");
}

/**
 * One line per rubric criterion, in the form "Capability: what the work
 * changed; what the controlled run showed for this submission; what was not
 * assessed". Built only from the evaluation and the submitted files; it never
 * describes the person.
 */
export function capabilityStatements(evaluation: EmployerAuthoredEvaluation, changes: SubmissionChanges | null): Array<{ criterionId: string; text: string }> {
  const acc = new Map(evaluation.acceptance.map((a) => [a.id, a]));
  const work = changes
    ? [changes.changed.length ? `changed ${listPaths(changes.changed)}` : "", changes.added.length ? `added ${listPaths(changes.added)}` : ""].filter(Boolean).join(" and ") || "submitted the starter files unchanged"
    : "";
  return evaluation.criteria.map((c) => {
    if (c.judgedBy === "reviewer") return { criterionId: c.id, text: `${c.label}: not assessed by the tests; a reviewer judges it from the submission.` };
    const linked = c.acceptanceCriterionIds.map((id) => acc.get(id)).filter((a): a is NonNullable<typeof a> => Boolean(a));
    const confirmed = linked.filter((a) => a.state === "confirmed");
    const notConfirmed = linked.filter((a) => a.state === "not_confirmed");
    const noResult = linked.filter((a) => a.state === "no_result");
    const run: string[] = [];
    if (confirmed.length) run.push(`the controlled run passed ${confirmed.map((a) => `${a.id} (${criterionText(a.text)})`).join(", ")} for this submission`);
    if (notConfirmed.length) run.push(`it did not pass ${notConfirmed.map((a) => `${a.id} (${criterionText(a.text)})`).join(", ")}`);
    if (noResult.length) run.push(`${noResult.map((a) => a.id).join(", ")} produced no result and ${noResult.length === 1 ? "was" : "were"} not assessed`);
    if (!linked.length) run.push("no test is linked to it, so it was not assessed");
    return { criterionId: c.id, text: `${c.label}: ${[work, ...run].filter(Boolean).join("; ")}.` };
  });
}

/** Plain text for pasting into an ATS or an email to the hiring panel. */
export function authoredBriefText(input: {
  candidate: string;
  role: string;
  task: string;
  brief: AuthoredDecisionBrief;
  followUps: AuthoredFollowUp[];
  capabilities?: Array<{ text: string }>;
}): string {
  const { brief } = input;
  const lines: string[] = [
    `${input.candidate}, ${input.role}`,
    `Work sample: ${input.task}`,
    "",
    `Acceptance criteria: ${brief.acceptance.confirmed} of ${brief.acceptance.total} confirmed by tests, ${brief.acceptance.notConfirmed} not confirmed, ${brief.acceptance.noResult} without a result.`,
  ];
  if (input.capabilities?.length) lines.push("", "Capabilities shown in this work:", ...input.capabilities.map((c) => `- ${c.text}`));
  const list = (title: string, items: string[]) => {
    if (!items.length) return;
    lines.push("", `${title}:`, ...items.map((i) => `- ${i}`));
  };
  list("Demonstrated", brief.demonstrated);
  list("Partially demonstrated", brief.partial);
  list("Concern observed", brief.concerns);
  list("Left for the reviewer", brief.notAssessed);
  if (input.followUps.length) {
    lines.push("", "Follow-up questions:");
    input.followUps.forEach((f, i) => lines.push(`${i + 1}. ${f.question}`, `   Based on: ${f.basis}`));
  }
  list("Limitations", brief.limitations);
  lines.push("", "Fydell reports what the tests and the submission show for this one work sample. It does not score the candidate, establish overall ability or make the decision.");
  return lines.join("\n");
}
