/**
 * Role-family catalog: one initial scenario blueprint per engineering family.
 *
 * Statuses are deliberately conservative. Only the backend scenario has a
 * runnable package (scenarios/webhook-retry-incident); every other family is
 * a substantive design at `draft` until its starter, harness and fixtures
 * exist and pass the same validation. `statusIsHonest` (lifecycle.ts) and
 * scripts/test-scenario-catalog.ts fail the build if an entry claims more
 * than its review records support.
 */
import type { CatalogEntry } from "./schema";

const NO_GPU = { requiresGpu: false, requiresPhysicalDevice: false } as const;

export const CATALOG: CatalogEntry[] = [
  {
    family: "backend",
    label: "Backend engineering",
    priority: 1,
    scopeDisclosure:
      "Covers service-side incident repair in a small Python webhook dispatcher: failure classification, bounded retries, idempotent delivery and a mid-task rate-limit change. It does not cover database design at scale, distributed systems operations or API design from scratch.",
    initialScenario: {
      id: "webhook-retry-incident",
      title: "Webhook retry incident (INC-2291)",
      version: "1.0.0",
      templateSlug: "webhook-retry-incident",
      effortMinutes: 60,
      responsibilityTags: ["incident repair", "api reliability", "idempotency", "regression testing", "handoff"],
      stackTags: ["python", "pytest", "webhooks", "http"],
      capabilitiesAssessed: [
        "Classifying transient versus permanent HTTP failures as a rule",
        "Durable idempotent delivery keyed on event and endpoint",
        "Keeping an existing test suite green while fixing a defect",
        "Adapting to a mid-task Retry-After requirement",
        "Writing a handoff an on-call reviewer can act on",
      ],
      capabilitiesNotAssessed: [
        "Designing a service or schema from scratch",
        "Operating production infrastructure",
        "Performance tuning under load",
        "Languages other than Python",
      ],
      blueprint: {
        businessSituation:
          "Kestrel Ledger's release 2.14 broke outbound webhooks: a merchant's 410 endpoint is hammered with retries, and an at-least-once event bus republish made another merchant ship an order twice.",
        candidateRole: "On-call backend engineer asked to ship a reviewable hotfix.",
        starterAssets: [
          "webhooks/ package (dispatcher, retry policy, store, transport, signing)",
          "Provided pytest suite with the two incident reproductions failing",
          "INCIDENT.md, CHANGELOG.md, runbook and delivery-worker log excerpt",
        ],
        intendedProblem:
          "is_retryable treats every status >= 400 as transient, and Dispatcher.enqueue always creates a new delivery for a republished event.",
        inScope: [
          "Retry classification",
          "Deduplication per (event, endpoint)",
          "Retry-After handling after the update",
          "Tests for the new behaviour",
        ],
        outOfScope: ["Dashboard replay tool", "Broad refactors", "Schema redesign beyond a small store change"],
        personas: [
          {
            id: "maya",
            kind: "engineering_teammate",
            role: "Maya, staff engineer and incident lead",
            knows: ["Runbook policy for 404", "Dedupe scope is per event and endpoint", "Hotfix size expectations"],
            doesNotKnow: ["The hidden tests", "How other candidates solved it"],
            escalation: "Points app problems to Fydell support; does not give code.",
          },
          {
            id: "partner_ops",
            kind: "operations_stakeholder",
            role: "Partner gateway operations contact (delivers the Retry-After update)",
            knows: ["Gateway rate-limit rollout", "Retry-After is whole seconds"],
            doesNotKnow: ["Kestrel's internal code"],
            escalation: "Refers implementation questions back to Maya.",
          },
        ],
        clarificationFacts: [
          { question: "Should 404 be retried?", answer: "Keep 404 permanent for the hotfix; call deploy-time 404s out as a risk." },
          { question: "Dedupe per event or per event and endpoint?", answer: "Per event and endpoint; one event fans out." },
          { question: "Does a republish after a failed first delivery create a new delivery?", answer: "No; replays go through the dashboard." },
        ],
        requirementUpdate: {
          summary:
            "On 429 or 503 with a whole-second Retry-After header, schedule the next attempt after that delay, capped at MAX_DELAY_SECONDS; the attempt cap still applies.",
          trigger: "Server milestone at 25 minutes with a guaranteed minimum response window; never randomized per candidate.",
          evaluationRelevance: "Scored only through the requirement_update hidden test group and the handoff; absent exposure marks the dimension insufficient evidence.",
        },
        expectedArtifacts: ["Code change under webhooks/", "Added or updated tests", "Four-field handoff"],
        dimensions: [
          {
            key: "correctness",
            label: "Incident fixed without regressions",
            kind: "hard_skill",
            demonstrated: "incident_fix and preserved_behaviour hidden groups pass on the accepted snapshot",
            partial: "One incident defect fixed, or a preserved-behaviour test regresses",
            notDemonstrated: "Neither incident test passes on the accepted snapshot",
          },
          {
            key: "engineering_judgment",
            label: "Fixes the rule, not the symptom",
            kind: "hard_skill",
            demonstrated: "Classification is a rule, dedupe key includes endpoint, change is hotfix-sized",
            partial: "Correct behaviour but special-cases incident values or sprawls",
            notDemonstrated: "Special-cases 410 or event id only",
          },
          {
            key: "requirement_change",
            label: "Adapts to the Retry-After update",
            kind: "collaboration",
            demonstrated: "requirement_update group passes and handoff explains how it was tested",
            partial: "Implemented without a test, or tested but capped incorrectly",
            notDemonstrated: "Update delivered and acknowledged but not addressed",
          },
          {
            key: "handoff",
            label: "Handoff a reviewer can act on",
            kind: "collaboration",
            demonstrated: "Testing claims match recorded runs; remaining risks are concrete",
            partial: "Accurate but omits the deploy-time 404 or already-sent duplicates risk",
            notDemonstrated: "Claims contradicted by test runs, or no handoff",
          },
        ],
        validApproaches: [
          "Explicit transient status set in retry.py; dedupe lookup in the dispatcher",
          "Range checks with 408/429 exceptions; dedupe enforced by a store index",
          "Retry-After parsing in a helper used by the dispatcher",
        ],
        defectiveFixtures: [
          "defect_410_only (special-cases 410)",
          "defect_dedupe_by_event_only (breaks fan-out)",
          "defect_never_retry_http",
          "defect_retry_after_uncapped",
          "partial_no_update",
        ],
        runtime: {
          execution: "remote_container",
          languages: ["Python 3.12", "pytest"],
          network: "denied",
          ...NO_GPU,
          notes: "Runs in Vercel Sandbox snapshot or the gVisor engineering-runner; hidden tests never leave the server.",
        },
      },
    },
    validation: {
      status: "expert_review",
      runnable: true,
      reviews: [
        {
          stage: "automated_validation",
          outcome: "passed",
          actorKind: "automation",
          actor: "scripts/validate-engineering-scenario.ts",
          date: "2026-09-29",
          scenarioVersion: "1.0.0",
          evidence: [
            "npm run validate:scenario: 17/17 checks (9 solution variants match .fydell/evaluation.json; tamper, conftest, weakened-test and infinite-loop fixtures pass)",
            "Local provider, Windows 11, Python 3.12.10; see docs/backend-verification.md",
          ],
        },
      ],
      blockers: [
        "SCEN-09: no qualified engineer other than the author has reviewed the scenario, rubric or hidden tests",
        "Live isolation checks for the chosen runner (RUN-01/02) not yet run",
        "No timing trial of the 60-minute estimate with outside engineers",
      ],
    },
  },
  {
    family: "fullstack",
    label: "Full-stack / product engineering",
    priority: 2,
    scopeDisclosure:
      "Covers one failed customer workflow that crosses a React form, a JSON API and a relational table. It does not cover visual design, large-scale frontend architecture or infrastructure.",
    initialScenario: {
      id: "fullstack-refund-workflow",
      title: "Refund request silently fails for some customers",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 75,
      responsibilityTags: ["end-to-end debugging", "api contracts", "user-facing errors", "integration tests"],
      stackTags: ["typescript", "react", "node", "sqlite", "vitest"],
      capabilitiesAssessed: [
        "Tracing a defect across UI, API and database layers",
        "Keeping client and server validation consistent",
        "Surfacing actionable user-facing errors instead of silent failure",
        "Writing an integration test that reproduces the defect",
      ],
      capabilitiesNotAssessed: ["Visual design quality", "Browser performance tuning", "Deployment and hosting"],
      blueprint: {
        businessSituation:
          "Support tickets show customers submitting refund requests that never reach the finance queue. The form shows success, the API returns 200, and no row exists.",
        candidateRole: "Product engineer on the payments squad.",
        starterAssets: [
          "Monorepo with web/ (React form), api/ (Express handler), db/ (SQLite migrations and seed)",
          "Vitest unit tests and one Playwright-free integration test harness using an in-process server",
          "Three support tickets with order ids and timestamps",
        ],
        intendedProblem:
          "The API swallows a unique-constraint violation for partially refunded orders and returns 200; the form treats any 2xx as success, and amounts with cents are rounded differently on client and server.",
        inScope: ["Error propagation from db to API to UI", "Amount validation parity", "Integration test for the ticketed case"],
        outOfScope: ["Redesigning the refund form", "Payment provider integration", "Authentication"],
        personas: [
          {
            id: "priya",
            kind: "product_stakeholder",
            role: "Priya, product manager for payments",
            knows: ["Partial refunds are allowed up to the captured amount", "Customers must see a reason when a refund is refused"],
            doesNotKnow: ["Database constraint details"],
            escalation: "Defers implementation choices to the engineering teammate.",
          },
          {
            id: "tomas",
            kind: "engineering_teammate",
            role: "Tomás, API owner",
            knows: ["Why the unique constraint exists", "Error envelope conventions ({ error: { code, message } })"],
            doesNotKnow: ["Hidden tests"],
            escalation: "Gives architecture context, not code.",
          },
        ],
        clarificationFacts: [
          { question: "Can a customer request a second partial refund?", answer: "Yes, while the total stays within the captured amount." },
          { question: "What should the UI show on refusal?", answer: "The server's reason, in the form, without clearing the input." },
        ],
        requirementUpdate: {
          summary: "Finance now requires a reason code on every refund request; existing clients must get a clear validation error rather than a 500.",
          trigger: "Milestone after the first integration test run, fallback at 35 minutes.",
          evaluationRelevance: "Scored through protected tests for the new field and the handoff.",
        },
        expectedArtifacts: ["Code changes across web/, api/, db/", "Integration test reproducing a ticket", "Handoff"],
        dimensions: [
          { key: "correctness", label: "Workflow works end to end", kind: "hard_skill", demonstrated: "Protected end-to-end tests pass, including second partial refund", partial: "Server fixed but UI still reports false success", notDemonstrated: "Silent failure remains" },
          { key: "consistency", label: "Client and server agree", kind: "hard_skill", demonstrated: "One shared validation rule or matching tests on both sides", partial: "Rules match for ticketed cases only", notDemonstrated: "Rounding mismatch remains" },
          { key: "user_errors", label: "Actionable user-facing errors", kind: "hard_skill", demonstrated: "Refusals show the server reason without losing input", partial: "Generic error shown", notDemonstrated: "Success shown on failure" },
          { key: "handoff", label: "Handoff and risk communication", kind: "collaboration", demonstrated: "Names data already affected and how to find it", partial: "Describes the fix only", notDemonstrated: "No handoff or inaccurate claims" },
        ],
        validApproaches: ["Shared validation module imported by client and server", "Server-authoritative validation with typed error codes mapped in the UI"],
        defectiveFixtures: ["Catches all errors and returns 400 without reason", "Fixes UI message but leaves the swallowed constraint error", "Removes the unique constraint"],
        runtime: { execution: "remote_container", languages: ["Node 22", "TypeScript"], network: "denied", ...NO_GPU, notes: "Headless; UI behaviour asserted through component tests, not a real browser." },
      },
    },
    validation: {
      status: "draft",
      runnable: false,
      reviews: [],
      blockers: ["Starter repository, protected tests and solution fixtures not built", "Runner image needs Node 22 alongside Python"],
    },
  },
  {
    family: "forward_deployed",
    label: "Forward-deployed / integration engineering",
    priority: 2,
    scopeDisclosure:
      "Covers clarifying one ambiguous customer request and integrating a supplied REST API with inconsistent data into a small sync job. It does not cover travel, live customer meetings, sales or long-running account management.",
    initialScenario: {
      id: "fde-inventory-sync",
      title: "Customer inventory sync with a messy supplier API",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 90,
      responsibilityTags: ["customer discovery", "api integration", "data reconciliation", "customer handoff"],
      stackTags: ["python", "rest", "json", "pytest"],
      capabilitiesAssessed: [
        "Asking the questions that resolve an ambiguous request before building",
        "Integrating an API with inconsistent pagination, units and ids",
        "Stating constraints and trade-offs to a non-engineer",
        "Writing a customer-facing handoff with next steps",
      ],
      capabilitiesNotAssessed: ["Live meeting presence", "Commercial negotiation", "Long-term account ownership"],
      blueprint: {
        businessSituation:
          "A retail customer says 'our stock counts are wrong in your dashboard' and wants a nightly sync from their supplier's API fixed before a promotion.",
        candidateRole: "Forward-deployed engineer assigned to the customer.",
        starterAssets: [
          "sync/ job with a client for a controlled fixture supplier API (served by the harness)",
          "Sample API responses showing mixed units (each vs case), duplicate SKUs and cursor pagination",
          "Customer email thread and a dashboard screenshot description",
        ],
        intendedProblem:
          "The sync stops after the first page, treats case quantities as units, and overwrites rather than reconciles duplicate SKUs.",
        inScope: ["Clarifying which counts are wrong", "Fixing pagination, units and duplicates", "Customer handoff"],
        outOfScope: ["Changing the supplier API", "Building a new dashboard"],
        personas: [
          {
            id: "dana",
            kind: "product_stakeholder",
            role: "Dana, customer operations lead (simulated customer)",
            knows: ["Which stores are affected", "Promotion date", "Case size is 12 for most SKUs but not all"],
            doesNotKnow: ["API details", "Code"],
            escalation: "Says 'I'll need to check with the supplier' for facts outside the brief.",
          },
          {
            id: "rui",
            kind: "engineering_teammate",
            role: "Rui, integrations engineer who wrote the original job",
            knows: ["Supplier API quirks list", "Why sync runs nightly"],
            doesNotKnow: ["Customer's promotion plans"],
            escalation: "Gives context, not fixes.",
          },
        ],
        clarificationFacts: [
          { question: "Which counts are wrong?", answer: "Only SKUs sold by the case; singles are right." },
          { question: "Where is the case size?", answer: "In the supplier's product endpoint as pack_size; missing means 1." },
        ],
        requirementUpdate: {
          summary: "The customer now needs the sync to flag, not silently fix, SKUs whose pack size changed since the last run.",
          trigger: "Customer message after the first successful sync run, fallback at 45 minutes.",
          evaluationRelevance: "Protected test for the flag output and the customer handoff's explanation.",
        },
        expectedArtifacts: ["Code change", "Tests", "Customer-facing summary", "Internal handoff"],
        dimensions: [
          { key: "discovery", label: "Clarifies before building", kind: "collaboration", demonstrated: "Asks which SKUs are wrong and where pack size lives before changing units", partial: "Asks after an incorrect first attempt", notDemonstrated: "Assumes and ships a wrong fix" },
          { key: "integration", label: "Correct integration", kind: "hard_skill", demonstrated: "All pages, correct units, reconciled duplicates in protected tests", partial: "Two of three defects fixed", notDemonstrated: "Sync still stops after one page" },
          { key: "constraints", label: "States constraints and trade-offs", kind: "collaboration", demonstrated: "Explains the pack-size assumption and its risk in plain language", partial: "Mentions it only in code comments", notDemonstrated: "Not mentioned" },
          { key: "customer_handoff", label: "Customer-ready handoff", kind: "collaboration", demonstrated: "Customer summary is accurate, non-technical and names next steps", partial: "Accurate but technical", notDemonstrated: "Missing or contradicts tests" },
        ],
        validApproaches: ["Normalize units at ingest using pack_size", "Reconcile in a staging table keyed by supplier SKU then apply"],
        defectiveFixtures: ["Multiplies every SKU by 12", "Fetches all pages but double-counts duplicates", "Correct code with a handoff promising supplier changes"],
        runtime: { execution: "remote_container", languages: ["Python 3.12"], network: "allowlisted_fixture_endpoints", ...NO_GPU, notes: "The supplier API is a harness-served fixture; no real external endpoints." },
      },
    },
    validation: {
      status: "draft",
      runnable: false,
      reviews: [],
      blockers: ["Fixture API server and starter not built", "Runner needs allowlisted loopback fixture endpoint support"],
    },
  },
  {
    family: "frontend",
    label: "Frontend engineering",
    priority: 3,
    scopeDisclosure:
      "Covers repairing one stateful React component with async, keyboard and error-state defects. It does not cover visual design, cross-browser rendering or large application architecture.",
    initialScenario: {
      id: "frontend-combobox-repair",
      title: "Search combobox loses results and traps keyboard users",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 60,
      responsibilityTags: ["state management", "accessibility", "async ui", "component tests"],
      stackTags: ["typescript", "react", "testing-library", "vitest"],
      capabilitiesAssessed: [
        "Fixing race conditions between async requests and rendered state",
        "Keyboard and screen-reader behaviour per the ARIA combobox pattern",
        "Visible, recoverable error states",
        "Behavioural component tests",
      ],
      capabilitiesNotAssessed: ["Visual design", "Real-browser rendering differences", "Bundle performance"],
      blueprint: {
        businessSituation: "Users report the product search shows results for an earlier query and keyboard users cannot leave the list.",
        candidateRole: "Frontend engineer on the web app team.",
        starterAssets: ["components/SearchCombobox.tsx with hooks", "Mock search API with controllable latency and failures", "Testing Library suite (some failing)"],
        intendedProblem: "Out-of-order responses overwrite newer results, Escape and Tab are swallowed, and failures render an empty list.",
        inScope: ["Stale response handling", "Keyboard interaction", "Error and retry state", "Tests"],
        outOfScope: ["Restyling", "Replacing the component library"],
        personas: [
          { id: "lena", kind: "product_stakeholder", role: "Lena, product designer", knows: ["Expected keyboard behaviour", "Error copy"], doesNotKnow: ["Code"], escalation: "Refers implementation to Sam." },
          { id: "sam", kind: "engineering_teammate", role: "Sam, frontend lead", knows: ["Project conventions", "Why the API has no cancellation"], doesNotKnow: ["Hidden tests"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "Should Tab select the highlighted option?", answer: "No; Tab moves focus on, Enter selects." },
          { question: "Retry automatically on failure?", answer: "No; show the error with a retry button." },
        ],
        requirementUpdate: {
          summary: "Search must debounce at 250ms and show a 'searching' status announced to screen readers.",
          trigger: "Milestone after the first passing test run, fallback at 30 minutes.",
          evaluationRelevance: "Protected tests for debounce and live-region status.",
        },
        expectedArtifacts: ["Component change", "Tests", "Handoff"],
        dimensions: [
          { key: "state", label: "Correct async state", kind: "hard_skill", demonstrated: "Latest query always wins in protected race tests", partial: "Race fixed but loading state wrong", notDemonstrated: "Stale results remain" },
          { key: "accessibility", label: "Keyboard and assistive technology", kind: "hard_skill", demonstrated: "Escape, Tab, arrows and aria attributes match the pattern", partial: "Keyboard fixed, aria incomplete", notDemonstrated: "Focus trap remains" },
          { key: "maintainability", label: "Maintainable change", kind: "hard_skill", demonstrated: "Small, tested, follows conventions", partial: "Works but duplicates logic", notDemonstrated: "Unreviewable rewrite" },
          { key: "handoff", label: "Handoff accuracy", kind: "collaboration", demonstrated: "Names untested browsers/AT honestly", partial: "Omits limits", notDemonstrated: "Claims untested behaviour" },
        ],
        validApproaches: ["Request id guard in a reducer", "AbortController-style ignore flag per effect"],
        defectiveFixtures: ["Debounce only (race remains)", "Keyboard fix that breaks mouse selection", "Error state that clears the query"],
        runtime: { execution: "remote_container", languages: ["Node 22", "TypeScript"], network: "denied", ...NO_GPU, notes: "jsdom-based; does not validate real screen readers or browsers." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Starter and fixtures not built", "Accessibility anchors need review by an accessibility specialist"] },
  },
  {
    family: "applied_ai",
    label: "Applied AI engineering",
    priority: 3,
    scopeDisclosure:
      "Covers improving one retrieval-augmented support assistant against supplied evaluation cases and a cost/latency budget, using a deterministic stub model. It does not cover model training, fine-tuning or live provider behaviour.",
    initialScenario: {
      id: "applied-ai-grounded-answers",
      title: "Support assistant cites the wrong policy",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 75,
      responsibilityTags: ["evaluation design", "retrieval", "grounding", "failure handling", "cost trade-offs"],
      stackTags: ["python", "embeddings", "rag", "pytest"],
      capabilitiesAssessed: [
        "Designing and extending evaluation cases before changing the system",
        "Improving retrieval so answers are grounded in the right source",
        "Refusing or escalating when sources do not support an answer",
        "Reasoning about cost and latency within a stated budget",
      ],
      capabilitiesNotAssessed: ["Model training or fine-tuning", "Behaviour of any specific live LLM provider", "Production MLOps"],
      blueprint: {
        businessSituation: "The support assistant quotes the 2024 refund policy for 2026 orders and invents a warranty term.",
        candidateRole: "Applied AI engineer on the support tooling team.",
        starterAssets: ["rag/ pipeline with chunker, retriever and prompt builder", "Deterministic stub model and embedding fixtures", "20 labelled evaluation cases, 5 held out on the server", "Token cost table and latency budget"],
        intendedProblem: "Chunks lose document dates, retrieval ignores policy versions, and the prompt lacks a refusal path.",
        inScope: ["Evaluation cases", "Retrieval and chunk metadata", "Refusal behaviour", "Budget reasoning"],
        outOfScope: ["Swapping model providers", "Fine-tuning"],
        personas: [
          { id: "noor", kind: "product_stakeholder", role: "Noor, support operations lead", knows: ["Which policies are current", "Escalation path to humans"], doesNotKnow: ["Retrieval internals"], escalation: "Defers technical detail." },
          { id: "ivan", kind: "engineering_teammate", role: "Ivan, ML platform engineer", knows: ["Budget: p95 under 2s, under $0.004 per answer", "Stub model behaviour"], doesNotKnow: ["Held-out cases"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "What if two policies apply?", answer: "Use the one effective on the order date; say which." },
          { question: "Can the assistant say it does not know?", answer: "Yes, and it should offer the human escalation link." },
        ],
        requirementUpdate: {
          summary: "Legal requires every answer to cite the policy id and effective date, or refuse.",
          trigger: "Milestone after the first evaluation run, fallback at 35 minutes.",
          evaluationRelevance: "Held-out citation cases and handoff.",
        },
        expectedArtifacts: ["Pipeline change", "New evaluation cases", "Short evaluation report", "Handoff"],
        dimensions: [
          { key: "evaluation_design", label: "Evaluation quality", kind: "hard_skill", demonstrated: "Adds cases that isolate the failure before fixing", partial: "Adds cases after the fix only", notDemonstrated: "No new cases" },
          { key: "grounding", label: "Grounded output", kind: "hard_skill", demonstrated: "Held-out cases cite correct policy or refuse", partial: "Correct policy without citation", notDemonstrated: "Fabrication remains" },
          { key: "tradeoffs", label: "Cost and latency reasoning", kind: "hard_skill", demonstrated: "Measured within budget with stated trade-off", partial: "Within budget, unexplained", notDemonstrated: "Exceeds budget" },
          { key: "limits", label: "Honest limitations", kind: "collaboration", demonstrated: "States that stub results do not predict live model behaviour", partial: "Partial caveats", notDemonstrated: "Claims production readiness" },
        ],
        validApproaches: ["Metadata filter on effective date before ranking", "Re-ranking with policy version plus a refusal threshold"],
        defectiveFixtures: ["Hard-codes answers for the visible cases", "Refuses everything", "Adds citations that do not resolve to sources"],
        runtime: { execution: "remote_container", languages: ["Python 3.12"], network: "denied", ...NO_GPU, notes: "Deterministic stub model; no live provider calls. An earlier browser-sandbox prototype (sim-engine ai-workflow-hardening) is a different runtime and is not counted here." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Stub model, fixtures and held-out cases not built for the desktop runner"] },
  },
  {
    family: "data_engineering",
    label: "Data engineering",
    priority: 4,
    scopeDisclosure: "Covers repairing one batch pipeline with duplicates, a schema change and late-arriving data on local files. It does not cover distributed compute clusters or streaming infrastructure.",
    initialScenario: {
      id: "data-pipeline-late-events",
      title: "Daily revenue job double-counts and drops late orders",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 75,
      responsibilityTags: ["data integrity", "idempotent loads", "schema evolution", "lineage"],
      stackTags: ["python", "sql", "duckdb", "pytest"],
      capabilitiesAssessed: ["Idempotent, re-runnable loads", "Handling late-arriving records", "Schema change handling", "Recovery and lineage notes"],
      capabilitiesNotAssessed: ["Spark/cluster tuning", "Streaming systems", "Warehouse administration"],
      blueprint: {
        businessSituation: "Finance's daily revenue report is 3% high on re-run days and misses orders that arrive after midnight.",
        candidateRole: "Data engineer owning the revenue pipeline.",
        starterAssets: ["pipeline/ with extract, transform and load steps over DuckDB", "Three days of raw order files including a renamed column", "Data contract document"],
        intendedProblem: "Loads append without keys, the partition filter uses ingestion date, and a renamed column becomes null.",
        inScope: ["Idempotent load", "Late data window", "Schema mapping", "Backfill plan"],
        outOfScope: ["Changing upstream producers", "Dashboard changes"],
        personas: [
          { id: "grace", kind: "product_stakeholder", role: "Grace, finance analyst", knows: ["Which days were wrong", "Report deadline 07:00"], doesNotKnow: ["Pipeline internals"], escalation: "Defers to Omar." },
          { id: "omar", kind: "operations_stakeholder", role: "Omar, data platform on-call", knows: ["Late data arrives up to 48h", "Rename happened on day 2"], doesNotKnow: ["Hidden checks"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "How late can orders arrive?", answer: "Up to 48 hours; later ones go to a correction job." },
          { question: "Is order_id unique?", answer: "Per source system; combine with source." },
        ],
        requirementUpdate: { summary: "Refunds now arrive as negative rows in the same feed and must net against the original order day.", trigger: "After first successful re-run, fallback at 40 minutes.", evaluationRelevance: "Protected reconciliation tests and backfill plan." },
        expectedArtifacts: ["Pipeline change", "Tests", "Backfill and lineage note"],
        dimensions: [
          { key: "integrity", label: "Data integrity", kind: "hard_skill", demonstrated: "Re-runs produce identical totals; late orders counted", partial: "Idempotent but late data dropped", notDemonstrated: "Double counting remains" },
          { key: "schema", label: "Schema change handling", kind: "hard_skill", demonstrated: "Explicit mapping with a failing check on unknown columns", partial: "Silent coalesce", notDemonstrated: "Nulls remain" },
          { key: "recovery", label: "Recovery plan", kind: "collaboration", demonstrated: "Backfill steps with verification queries", partial: "Backfill without verification", notDemonstrated: "None" },
        ],
        validApproaches: ["Merge on (source, order_id) with an event-time window", "Rebuild affected partitions from raw files deterministically"],
        defectiveFixtures: ["Dedupe on order_id alone", "Widens window without idempotency", "Fixes totals by hard-coded adjustment"],
        runtime: { execution: "remote_container", languages: ["Python 3.12", "DuckDB"], network: "denied", ...NO_GPU, notes: "Local files only; does not validate warehouse-specific behaviour." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Data fixtures and protected reconciliation tests not built"] },
  },
  {
    family: "ml_engineering",
    label: "ML engineering",
    priority: 4,
    scopeDisclosure: "Covers diagnosing leakage and flawed validation in one small tabular model pipeline on CPU. It does not cover deep learning, large-scale training or research novelty.",
    initialScenario: {
      id: "ml-churn-leakage",
      title: "Churn model looks great offline and fails in production",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 75,
      responsibilityTags: ["experimental validity", "leakage detection", "reproducibility", "evaluation reasoning"],
      stackTags: ["python", "scikit-learn", "pandas"],
      capabilitiesAssessed: ["Detecting target leakage", "Choosing a validation split that matches deployment", "Reproducible experiments", "Explaining metric changes honestly"],
      capabilitiesNotAssessed: ["Deep learning", "GPU training", "Novel modelling research"],
      blueprint: {
        businessSituation: "A churn model reported 0.94 AUC offline but performs near chance on last month's customers.",
        candidateRole: "ML engineer asked to explain and repair the evaluation.",
        starterAssets: ["train.py and features.py", "Seeded synthetic customer dataset", "Previous experiment report"],
        intendedProblem: "A feature derived from cancellation date leaks the label and random splits mix time periods.",
        inScope: ["Finding leakage", "Time-based validation", "Reproducible run", "Honest report"],
        outOfScope: ["Collecting new data", "Deploying the model"],
        personas: [
          { id: "ines", kind: "product_stakeholder", role: "Inès, retention lead", knows: ["How predictions are used", "Monthly scoring cadence"], doesNotKnow: ["Modelling details"], escalation: "Defers to Kai." },
          { id: "kai", kind: "engineering_teammate", role: "Kai, ML platform engineer", knows: ["Feature generation timing", "Seeds and environment"], doesNotKnow: ["Hidden checks"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "When are features computed relative to the prediction date?", answer: "Nightly, using data up to the day before scoring." },
          { question: "Is a lower AUC acceptable?", answer: "Yes, if it reflects real performance." },
        ],
        requirementUpdate: { summary: "Retention wants calibrated probabilities for budget planning, not just ranking.", trigger: "After first corrected evaluation, fallback at 40 minutes.", evaluationRelevance: "Calibration check and report." },
        expectedArtifacts: ["Corrected pipeline", "Reproducible run log", "Evaluation note"],
        dimensions: [
          { key: "validity", label: "Experimental validity", kind: "hard_skill", demonstrated: "Leaky feature removed and time split used; protected check passes", partial: "One of the two fixed", notDemonstrated: "Leakage remains" },
          { key: "reproducibility", label: "Reproducibility", kind: "hard_skill", demonstrated: "Seeded run reproduces reported metrics", partial: "Seeds set but metrics differ", notDemonstrated: "Not reproducible" },
          { key: "reporting", label: "Honest evaluation reasoning", kind: "collaboration", demonstrated: "Explains the lower metric as the truthful one", partial: "Reports numbers without explanation", notDemonstrated: "Claims improvement from leakage" },
        ],
        validApproaches: ["Drop the leaky feature and use a rolling-origin split", "Rebuild features as of prediction date with a time split"],
        defectiveFixtures: ["Time split with leakage retained", "Removes leakage but tunes on the test month"],
        runtime: { execution: "remote_container", languages: ["Python 3.12", "scikit-learn"], network: "denied", ...NO_GPU, notes: "CPU-only, bounded dataset." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Synthetic dataset generator and protected checks not built"] },
  },
  {
    family: "mlops",
    label: "MLOps / model serving",
    priority: 5,
    scopeDisclosure: "Covers repairing one model-serving service's rollout and monitoring using supplied drift and latency evidence, with a CPU stub model. It does not validate GPU serving, autoscaling on real clusters or a specific cloud.",
    initialScenario: {
      id: "mlops-canary-rollback",
      title: "Canary model shipped without a rollback path",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 75,
      responsibilityTags: ["serving reliability", "observability", "rollout and rollback"],
      stackTags: ["python", "fastapi", "prometheus-format metrics"],
      capabilitiesAssessed: ["Safe rollout and rollback logic", "Meaningful serving metrics and alerts", "Reading drift and latency evidence"],
      capabilitiesNotAssessed: ["GPU serving", "Real cluster autoscaling", "Cloud-provider specifics"],
      blueprint: {
        businessSituation: "A new model version was routed 100% after a canary with no latency guard; p95 doubled and drift alerts were ignored.",
        candidateRole: "MLOps engineer on the serving team.",
        starterAssets: ["serve/ FastAPI app with router and model registry stub", "Recorded drift and latency metric snapshots", "Rollout config"],
        intendedProblem: "Router ignores canary percentage after restart; no automatic rollback on SLO breach; metrics lack model version labels.",
        inScope: ["Router correctness", "Rollback rule", "Metrics labelling", "Runbook note"],
        outOfScope: ["Retraining", "Infrastructure provisioning"],
        personas: [
          { id: "ola", kind: "operations_stakeholder", role: "Ola, SRE on-call", knows: ["SLO: p95 < 300ms", "Alert routing"], doesNotKnow: ["Model internals"], escalation: "Context only." },
          { id: "ben", kind: "engineering_teammate", role: "Ben, ML engineer who trained v2", knows: ["Expected drift after launch"], doesNotKnow: ["Serving code"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "Rollback automatically or page a human?", answer: "Automatically to the previous version, then page." },
          { question: "Is some drift expected?", answer: "Yes, feature X shifts seasonally; alert on others." },
        ],
        requirementUpdate: { summary: "Rollback must also trigger on error rate above 2% over five minutes.", trigger: "After first router test run, fallback at 35 minutes.", evaluationRelevance: "Protected rollback tests." },
        expectedArtifacts: ["Code change", "Tests", "Runbook entry"],
        dimensions: [
          { key: "reliability", label: "Serving reliability", kind: "hard_skill", demonstrated: "Canary persists and rollback triggers correctly in protected tests", partial: "One path fixed", notDemonstrated: "Neither" },
          { key: "observability", label: "Observability", kind: "hard_skill", demonstrated: "Version-labelled metrics feed the rule", partial: "Metrics labelled, rule separate", notDemonstrated: "Unlabelled" },
          { key: "operational_plan", label: "Operational handoff", kind: "collaboration", demonstrated: "Runbook names triggers, owners and verification", partial: "Vague", notDemonstrated: "None" },
        ],
        validApproaches: ["Persist rollout state in the registry", "Stateless router reading config with SLO evaluator"],
        defectiveFixtures: ["Rollback on any drift", "Hard-coded canary 10%"],
        runtime: { execution: "remote_container", languages: ["Python 3.12"], network: "denied", ...NO_GPU, notes: "Simulated traffic and recorded metrics; not a live cluster." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Traffic simulator and metric fixtures not built"] },
  },
  {
    family: "platform_sre",
    label: "Platform / DevOps / SRE",
    priority: 5,
    scopeDisclosure: "The initial task covers one isolated service incident: diagnosing a bad config rollout from logs and metrics, making a safe change and handing over an operational plan. It does not cover cloud account administration, networking at scale, on-call rotation design or the full Platform/DevOps/SRE role.",
    initialScenario: {
      id: "sre-config-rollout-incident",
      title: "Connection pool exhaustion after a config rollout",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 60,
      responsibilityTags: ["incident diagnosis", "safe changes", "recovery", "observability"],
      stackTags: ["linux", "yaml config", "python", "logs"],
      capabilitiesAssessed: ["Diagnosis from logs and metrics", "Safe, reversible change", "Recovery verification", "Operational handoff"],
      capabilitiesNotAssessed: ["Cloud IAM and networking", "Kubernetes cluster operations", "Capacity planning"],
      blueprint: {
        businessSituation: "After a config rollout, the orders service returns 503s under normal load.",
        candidateRole: "SRE responding to the incident.",
        starterAssets: ["Service with config files and a load simulator", "Log and metric excerpts", "Deploy history"],
        intendedProblem: "Pool size was reduced and a retry loop without jitter amplifies load.",
        inScope: ["Diagnosis", "Config and retry fix", "Verification under simulated load", "Postmortem notes"],
        outOfScope: ["Rewriting the service", "Real infrastructure"],
        personas: [
          { id: "ana", kind: "operations_stakeholder", role: "Ana, incident commander", knows: ["Customer impact", "Change freeze rules"], doesNotKnow: ["Root cause"], escalation: "Asks for status updates." },
          { id: "leo", kind: "engineering_teammate", role: "Leo, service owner", knows: ["Why pool size changed"], doesNotKnow: ["Hidden checks"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "Can I roll back the whole deploy?", answer: "Yes, but it also reverts a security fix; prefer a targeted change." },
          { question: "What load is normal?", answer: "200 requests per second at peak." },
        ],
        requirementUpdate: { summary: "The incident commander needs a status update and an ETA before any change is applied.", trigger: "Fifteen minutes in, or on first config edit.", evaluationRelevance: "Communication dimension only." },
        expectedArtifacts: ["Config/code change", "Verification output", "Status update", "Operational plan"],
        dimensions: [
          { key: "diagnosis", label: "Diagnosis", kind: "hard_skill", demonstrated: "Names both causes with evidence", partial: "One cause", notDemonstrated: "Guesswork" },
          { key: "safe_change", label: "Safe change and recovery", kind: "hard_skill", demonstrated: "Targeted change verified under simulated load", partial: "Full rollback", notDemonstrated: "Unverified change" },
          { key: "communication", label: "Incident communication", kind: "collaboration", demonstrated: "Accurate status update with uncertainty stated", partial: "Update without ETA or risk", notDemonstrated: "None" },
        ],
        validApproaches: ["Restore pool size and add jittered backoff", "Circuit breaker plus pool restore"],
        defectiveFixtures: ["Raises pool size tenfold", "Full rollback reverting the security fix"],
        runtime: { execution: "remote_container", languages: ["Python 3.12", "bash"], network: "denied", ...NO_GPU, notes: "Simulated service and load inside the sandbox." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Load simulator and incident fixtures not built"] },
  },
  {
    family: "mobile",
    label: "Mobile engineering",
    priority: 5,
    scopeDisclosure: "Declared platform: React Native logic layer tested headlessly. Covers lifecycle and network-failure handling in app state. A desktop preview or headless test does not validate on-device behaviour; the task stays unavailable for purchase until a device or emulator farm is part of the runtime.",
    initialScenario: {
      id: "mobile-offline-checkout",
      title: "Checkout loses the cart after backgrounding offline",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 75,
      responsibilityTags: ["app lifecycle", "offline handling", "state persistence", "tests"],
      stackTags: ["typescript", "react-native", "jest"],
      capabilitiesAssessed: ["Persisting state across lifecycle events", "Queueing actions offline", "Clear error handling", "Tests for lifecycle paths"],
      capabilitiesNotAssessed: ["On-device performance", "Native module development", "Store release process"],
      blueprint: {
        businessSituation: "Customers lose their cart when the app is backgrounded on a poor connection.",
        candidateRole: "Mobile engineer on the commerce app.",
        starterAssets: ["App logic layer with store and API client", "Lifecycle and network simulators", "Jest tests"],
        intendedProblem: "State persists only on explicit save; offline submits are dropped rather than queued.",
        inScope: ["Persistence on background", "Offline queue", "User messaging"],
        outOfScope: ["Native code", "UI redesign"],
        personas: [
          { id: "mia", kind: "product_stakeholder", role: "Mia, product owner", knows: ["Carts should survive 24h"], doesNotKnow: ["Code"], escalation: "Defers." },
          { id: "raj", kind: "engineering_teammate", role: "Raj, mobile lead", knows: ["Storage limits", "API idempotency keys"], doesNotKnow: ["Hidden tests"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "Retry submits automatically when back online?", answer: "Yes, once, with the same idempotency key." },
          { question: "How long to keep a cart?", answer: "24 hours." },
        ],
        requirementUpdate: { summary: "Prices may change while offline; show the new total before resubmitting.", trigger: "After first passing lifecycle test, fallback at 35 minutes.", evaluationRelevance: "Protected tests for price change prompt." },
        expectedArtifacts: ["Code change", "Tests", "Handoff naming device testing not performed"],
        dimensions: [
          { key: "lifecycle", label: "Lifecycle correctness", kind: "hard_skill", demonstrated: "Cart survives background/kill in simulator tests", partial: "Background only", notDemonstrated: "Lost" },
          { key: "offline", label: "Offline behaviour", kind: "hard_skill", demonstrated: "Queued once with idempotency key", partial: "Queued, may duplicate", notDemonstrated: "Dropped" },
          { key: "limits", label: "Honest limits", kind: "collaboration", demonstrated: "States no device testing was possible", partial: "Partial", notDemonstrated: "Claims device-verified" },
        ],
        validApproaches: ["Persist on AppState change with a versioned schema", "Write-through store with an outbox queue"],
        defectiveFixtures: ["Retries forever", "Persists without expiry"],
        runtime: { execution: "device_farm", languages: ["TypeScript"], network: "denied", requiresGpu: false, requiresPhysicalDevice: true, notes: "Needs emulator/device execution before sale; headless simulators alone are insufficient." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["No emulator or device farm in the execution runtime", "Starter and fixtures not built"] },
  },
  {
    family: "qa_automation",
    label: "QA / test automation",
    priority: 4,
    scopeDisclosure: "Covers designing automated tests for a deliberately defective small web API and filing reproducible defect reports. It does not cover manual exploratory testing at scale or test-management tooling.",
    initialScenario: {
      id: "qa-booking-api-defects",
      title: "Find and report defects in a booking API before release",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 60,
      responsibilityTags: ["test design", "meaningful assertions", "defect reporting"],
      stackTags: ["python", "pytest", "http"],
      capabilitiesAssessed: ["Selecting high-value test cases", "Assertions that detect real defects", "Reproducible defect reports"],
      capabilitiesNotAssessed: ["Load testing", "UI automation frameworks", "Test management processes"],
      blueprint: {
        businessSituation: "A booking API ships tomorrow; the team suspects edge-case defects around time zones and capacity.",
        candidateRole: "Test automation engineer.",
        starterAssets: ["Running booking API (fixture) with seeded defects", "API spec", "Empty tests/ folder with helpers"],
        intendedProblem: "Five seeded defects: off-by-one capacity, DST booking shift, missing validation, race on last seat, wrong status code.",
        inScope: ["Automated tests", "Defect reports", "Risk summary"],
        outOfScope: ["Fixing the API"],
        personas: [
          { id: "eva", kind: "product_stakeholder", role: "Eva, release manager", knows: ["Release criteria", "Priority of defects"], doesNotKnow: ["Seeded defect list"], escalation: "Defers." },
          { id: "jon", kind: "engineering_teammate", role: "Jon, API developer", knows: ["Intended behaviour per spec"], doesNotKnow: ["Seeded defect list"], escalation: "Clarifies spec only." },
        ],
        clarificationFacts: [
          { question: "Which time zone are bookings in?", answer: "The venue's local time zone." },
          { question: "Is overbooking ever allowed?", answer: "No." },
        ],
        requirementUpdate: { summary: "A hotfix build is deployed; re-run your suite and report which defects are fixed.", trigger: "At 35 minutes.", evaluationRelevance: "Regression reporting accuracy." },
        expectedArtifacts: ["Test suite", "Defect reports with reproduction steps", "Release risk summary"],
        dimensions: [
          { key: "detection", label: "Defect detection", kind: "hard_skill", demonstrated: "Tests fail on at least four seeded defects and pass on the fixed build", partial: "Two or three", notDemonstrated: "One or none" },
          { key: "assertions", label: "Meaningful assertions", kind: "hard_skill", demonstrated: "No false positives on the correct reference build", partial: "Some brittle assertions", notDemonstrated: "Tests pass on broken build" },
          { key: "reporting", label: "Reproducible reports", kind: "collaboration", demonstrated: "Each report reproduces from its steps", partial: "Missing steps", notDemonstrated: "Vague" },
        ],
        validApproaches: ["Boundary-value tests per endpoint", "Property-style tests on capacity invariants"],
        defectiveFixtures: ["Tests asserting implementation details", "Snapshot tests of buggy output"],
        runtime: { execution: "remote_container", languages: ["Python 3.12"], network: "allowlisted_fixture_endpoints", ...NO_GPU, notes: "Candidate tests run against reference, seeded and hotfix builds." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Three API builds (reference, seeded, hotfix) not built"] },
  },
  {
    family: "application_security",
    label: "Application security",
    priority: 5,
    scopeDisclosure: "Covers investigating and remediating one seeded vulnerability in a closed lab web app. It does not validate penetration testing, cloud security, security operations or every security role.",
    initialScenario: {
      id: "appsec-idor-remediation",
      title: "Invoice download exposes other customers' invoices",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 60,
      responsibilityTags: ["threat reasoning", "remediation", "regression verification"],
      stackTags: ["python", "flask", "sql"],
      capabilitiesAssessed: ["Confirming and scoping an access-control flaw", "Fixing at the right layer", "Regression tests for the fix", "Impact communication"],
      capabilitiesNotAssessed: ["Network penetration testing", "Cloud security", "Incident response operations"],
      blueprint: {
        businessSituation: "A bug bounty report says invoices can be downloaded by changing a number in the URL.",
        candidateRole: "Application security engineer.",
        starterAssets: ["Closed lab Flask app with seeded users", "Bug bounty report", "Access logs excerpt"],
        intendedProblem: "Object-level authorization missing on two endpoints, one not named in the report.",
        inScope: ["Confirm, scope, fix, test", "Impact assessment from logs"],
        outOfScope: ["Attacking anything outside the lab"],
        personas: [
          { id: "zoe", kind: "product_stakeholder", role: "Zoe, head of support", knows: ["Customer notification process"], doesNotKnow: ["Code"], escalation: "Defers." },
          { id: "abe", kind: "engineering_teammate", role: "Abe, billing service owner", knows: ["Endpoint history"], doesNotKnow: ["Second vulnerable endpoint"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "Can admins view all invoices?", answer: "Yes, support admins only." },
          { question: "How far back do logs go?", answer: "30 days." },
        ],
        requirementUpdate: { summary: "Legal needs the count of customers whose invoices may have been accessed.", trigger: "After the first fix commit, fallback at 35 minutes.", evaluationRelevance: "Impact assessment accuracy." },
        expectedArtifacts: ["Fix", "Regression tests", "Impact note"],
        dimensions: [
          { key: "remediation", label: "Remediation", kind: "hard_skill", demonstrated: "Both endpoints fixed centrally; protected exploit tests fail to exploit", partial: "Reported endpoint only", notDemonstrated: "Exploit still works" },
          { key: "verification", label: "Regression verification", kind: "hard_skill", demonstrated: "Tests cover owner, other user and admin", partial: "Owner case only", notDemonstrated: "None" },
          { key: "impact", label: "Impact communication", kind: "collaboration", demonstrated: "Accurate count with method and uncertainty", partial: "Count without method", notDemonstrated: "None or wrong" },
        ],
        validApproaches: ["Ownership check in a shared decorator", "Query scoped by current user in the data layer"],
        defectiveFixtures: ["Obscures ids with UUIDs only", "Fixes the named endpoint only"],
        runtime: { execution: "remote_container", languages: ["Python 3.12"], network: "denied", ...NO_GPU, notes: "Closed lab; no outbound network." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Lab app and exploit tests not built", "Needs review by a qualified security engineer"] },
  },
  {
    family: "systems_embedded",
    label: "Systems / embedded / firmware",
    priority: 5,
    scopeDisclosure: "Covers a constrained concurrency and protocol-framing task in a host-side harness with a simulated UART. An emulator or harness does not validate real hardware timing or electrical behaviour; hardware-dependent variants stay unavailable.",
    initialScenario: {
      id: "embedded-ring-buffer-framing",
      title: "Sensor frames corrupted under burst traffic",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 75,
      responsibilityTags: ["concurrency", "resource limits", "protocol correctness"],
      stackTags: ["c", "cmake", "unity-test"],
      capabilitiesAssessed: ["Interrupt-safe ring buffer logic", "Frame parsing with checksums", "Fixed memory budgets", "Low-level reasoning in a handoff"],
      capabilitiesNotAssessed: ["Real hardware timing", "Board bring-up", "Electrical debugging"],
      blueprint: {
        businessSituation: "Field units drop or corrupt sensor frames during bursts.",
        candidateRole: "Firmware engineer.",
        starterAssets: ["C ring buffer and frame parser", "Simulated ISR/main-loop harness", "Captured byte streams"],
        intendedProblem: "Head/tail race under ISR preemption and a parser that resyncs incorrectly after a bad checksum.",
        inScope: ["Race fix", "Parser resync", "Tests in harness"],
        outOfScope: ["Hardware changes", "RTOS migration"],
        personas: [
          { id: "hana", kind: "engineering_teammate", role: "Hana, firmware lead", knows: ["Memory budget 2KB", "No dynamic allocation"], doesNotKnow: ["Hidden streams"], escalation: "Context only." },
          { id: "felix", kind: "operations_stakeholder", role: "Felix, field support", knows: ["Burst patterns from logs"], doesNotKnow: ["Code"], escalation: "Defers." },
        ],
        clarificationFacts: [
          { question: "Can I disable interrupts?", answer: "Briefly, under 10 cycles in the simulator's cost model." },
          { question: "Drop or block when full?", answer: "Drop newest and count drops." },
        ],
        requirementUpdate: { summary: "Protocol v2 adds a length byte; support both versions.", trigger: "After first passing harness run, fallback at 40 minutes.", evaluationRelevance: "Protected v2 stream tests." },
        expectedArtifacts: ["C changes", "Harness tests", "Handoff"],
        dimensions: [
          { key: "concurrency", label: "Concurrency correctness", kind: "hard_skill", demonstrated: "No corruption across seeded preemption schedules", partial: "Passes some schedules", notDemonstrated: "Race remains" },
          { key: "protocol", label: "Protocol correctness", kind: "hard_skill", demonstrated: "Resyncs correctly on all corrupted streams", partial: "Most", notDemonstrated: "Loses sync" },
          { key: "resources", label: "Resource behaviour", kind: "hard_skill", demonstrated: "Within memory budget with drop counter", partial: "Within budget without counter", notDemonstrated: "Exceeds budget" },
        ],
        validApproaches: ["Single-producer single-consumer indices with memory barriers", "Short critical section with interrupt masking"],
        defectiveFixtures: ["Mutex in ISR", "Large buffer masking the race"],
        runtime: { execution: "emulator", languages: ["C11"], network: "denied", ...NO_GPU, notes: "Host harness simulates preemption deterministically; does not reproduce real hardware." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Deterministic preemption harness not built", "Runner image needs a C toolchain"] },
  },
  {
    family: "game_graphics",
    label: "Game / graphics engineering",
    priority: 5,
    scopeDisclosure: "Covers a bounded frame-update and numerical defect in a deterministic CPU simulation harness. It does not validate GPU rendering, shader work or engine-specific tooling; GPU-dependent variants stay unavailable.",
    initialScenario: {
      id: "game-fixed-timestep",
      title: "Physics jitters and tunnels at low frame rates",
      version: "0.1.0",
      templateSlug: null,
      effortMinutes: 75,
      responsibilityTags: ["frame/update behaviour", "numerical correctness", "measured performance"],
      stackTags: ["c++", "cmake", "catch2"],
      capabilitiesAssessed: ["Fixed-timestep update loops", "Numerical stability", "Measuring performance reproducibly"],
      capabilitiesNotAssessed: ["GPU rendering", "Shader programming", "Engine editor tooling"],
      blueprint: {
        businessSituation: "Players on slower machines see objects pass through walls and jitter.",
        candidateRole: "Gameplay engineer.",
        starterAssets: ["C++ simulation loop and collision code", "Deterministic frame-time traces", "Catch2 tests and a benchmark harness"],
        intendedProblem: "Variable timestep integration and discrete collision checks tunnel at large dt.",
        inScope: ["Fixed timestep with interpolation", "Collision fix", "Benchmark evidence"],
        outOfScope: ["Rendering", "Asset pipeline"],
        personas: [
          { id: "yui", kind: "product_stakeholder", role: "Yui, game designer", knows: ["Feel requirements"], doesNotKnow: ["Code"], escalation: "Defers." },
          { id: "max", kind: "engineering_teammate", role: "Max, engine programmer", knows: ["Frame budget 4ms for physics"], doesNotKnow: ["Hidden traces"], escalation: "Context only." },
        ],
        clarificationFacts: [
          { question: "What timestep?", answer: "60Hz simulation; render may vary." },
          { question: "Max objects?", answer: "500." },
        ],
        requirementUpdate: { summary: "Replays must be deterministic across runs for the same input trace.", trigger: "After first passing test run, fallback at 40 minutes.", evaluationRelevance: "Protected determinism test." },
        expectedArtifacts: ["Code changes", "Tests", "Benchmark note"],
        dimensions: [
          { key: "update_loop", label: "Frame/update behaviour", kind: "hard_skill", demonstrated: "No tunnelling across all traces", partial: "Most traces", notDemonstrated: "Tunnelling remains" },
          { key: "numerics", label: "Numerical correctness", kind: "hard_skill", demonstrated: "Energy/position within tolerance and deterministic", partial: "Within tolerance, non-deterministic", notDemonstrated: "Unstable" },
          { key: "performance", label: "Measured performance", kind: "hard_skill", demonstrated: "Within budget in the reproducible benchmark", partial: "Over budget with explanation", notDemonstrated: "Unmeasured claims" },
        ],
        validApproaches: ["Accumulator fixed step with interpolation", "Swept collision with substeps"],
        defectiveFixtures: ["Caps dt only", "Substeps that blow the frame budget"],
        runtime: { execution: "remote_container", languages: ["C++17"], network: "denied", ...NO_GPU, notes: "CPU-only deterministic harness; any GPU variant would need remote_container_gpu." },
      },
    },
    validation: { status: "draft", runnable: false, reviews: [], blockers: ["Harness, traces and benchmark not built", "Runner image needs a C++ toolchain"] },
  },
];
