import { getAdminSession } from "@/lib/auth";
import { getCandidateFull } from "@/lib/db";
import { RUBRIC_FIELDS, type Score, type Stage } from "@/lib/types";
import { STAGE_LABELS } from "@/lib/scenario";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const NAVY = rgb(0.106, 0.145, 0.314); // #1B2550
const TEAL = rgb(0.078, 0.722, 0.651); // #14B8A6
const CORAL = rgb(0.956, 0.247, 0.369); // #F43F5E
const INK = rgb(0.227, 0.267, 0.36);
const MUTED = rgb(0.42, 0.45, 0.53);

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getAdminSession();
  if (!session) return new Response("Unauthorized", { status: 401 });

  const { id } = await params;
  const full = await getCandidateFull(id);
  if (!full) return new Response("Not found", { status: 404 });

  const { candidate, employer, session: sess, responses, score } = full;
  const answers: Record<string, string> = {};
  for (const r of responses) answers[r.stage] = r.response_text ?? "";

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]); // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const margin = 50;
  const width = page.getWidth() - margin * 2;
  let y = page.getHeight() - margin;

  function text(
    s: string,
    size: number,
    f = font,
    color = INK,
    indent = 0
  ): void {
    const maxWidth = width - indent;
    const words = s.split(/\s+/);
    let line = "";
    const lines: string[] = [];
    for (const w of words) {
      const test = line ? `${line} ${w}` : w;
      if (f.widthOfTextAtSize(test, size) > maxWidth && line) {
        lines.push(line);
        line = w;
      } else {
        line = test;
      }
    }
    if (line) lines.push(line);
    for (const ln of lines) {
      page.drawText(ln, { x: margin + indent, y, size, font: f, color });
      y -= size * 1.35;
    }
  }

  function gap(px: number) {
    y -= px;
  }

  function rule() {
    page.drawLine({
      start: { x: margin, y: y + 4 },
      end: { x: margin + width, y: y + 4 },
      thickness: 1,
      color: rgb(0.886, 0.902, 0.933)
    });
    gap(10);
  }

  // Brand bar
  page.drawRectangle({
    x: 0,
    y: page.getHeight() - 8,
    width: page.getWidth(),
    height: 8,
    color: TEAL
  });

  text("fydell", 16, bold, NAVY);
  gap(2);
  text("Candidate Simulation Report - Fydell", 10, font, MUTED);
  gap(14);

  text(candidate.name, 22, bold, NAVY);
  gap(2);
  text(`${employer.name}  |  ${candidate.role}`, 11, font, INK);
  gap(2);
  const timeStr =
    sess?.time_spent_seconds != null
      ? `${Math.floor(sess.time_spent_seconds / 60)}m ${sess.time_spent_seconds % 60}s`
      : "-";
  const submitted = sess?.submitted_at
    ? new Date(sess.submitted_at).toLocaleString()
    : "-";
  text(
    `Status: ${candidate.status}    Time spent: ${timeStr}    Submitted: ${submitted}`,
    10,
    font,
    MUTED
  );
  gap(16);
  rule();

  // Scoring rubric
  const checkedCount = score
    ? RUBRIC_FIELDS.filter((f) => score[f.key as keyof Score] === true).length
    : 0;
  text(`Scoring  (${checkedCount}/${RUBRIC_FIELDS.length})`, 13, bold, NAVY);
  gap(8);
  for (const f of RUBRIC_FIELDS) {
    const on = score ? score[f.key as keyof Score] === true : false;
    page.drawText(on ? "[x]" : "[ ]", {
      x: margin,
      y,
      size: 10,
      font: bold,
      color: on ? TEAL : CORAL
    });
    text(f.label, 10, font, INK, 26);
    gap(2);
  }
  gap(10);
  rule();

  // Key verbatim quotes
  text("Key responses (verbatim)", 13, bold, NAVY);
  gap(8);

  const quoteStages: Stage[] = ["manager_read", "final_q1", "final_q2"];
  for (const stage of quoteStages) {
    let body = (answers[stage] ?? "").trim();
    if (!body) body = "No response.";
    if (body.length > 460) body = body.slice(0, 457) + "...";
    text(STAGE_LABELS[stage], 9, bold, TEAL);
    gap(2);
    text(body, 10, font, INK);
    gap(8);
    if (y < margin + 40) break; // keep it on one page
  }

  // Footer
  page.drawText(
    `Generated by Fydell | ${new Date().toLocaleDateString()}`,
    { x: margin, y: margin - 14, size: 8, font, color: MUTED }
  );

  const bytes = await pdf.save();
  const filename = `fydell-${candidate.name.replace(/\s+/g, "-").toLowerCase()}.pdf`;

  return new Response(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`
    }
  });
}
