import MarketingShell from "@/components/layout/MarketingShell";
import { Reveal } from "@/components/motion/Reveal";
import { Container, ButtonLink } from "@/components/marketing/ui";
import PageHero from "@/components/marketing/PageHero";
import FinalCTA from "@/components/marketing/FinalCTA";

export const metadata = {
  title: "Project Relay · Fydell",
  description:
    "Project Relay is a 50-minute simulated deployment session: a real customer scenario, a real terminal, a mid-session curveball, and one immutable submission.",
};

const STAGES = [
  {
    title: "Consent + setup",
    body: "Every FDE sees exactly what's recorded before they start: file saves, command runs, chat messages, and the final submission.",
  },
  {
    title: "50-minute session",
    body: "A real customer scenario with a working codebase, an allowlisted terminal (test, pytest, evals, preview), and a bounded customer chat.",
  },
  {
    title: "Mid-session curveball",
    body: "Partway through, something changes — a rate limit, a schema drift, a policy question — and the FDE has to adapt in real time.",
  },
  {
    title: "One immutable submission",
    body: "When the FDE submits, their files are frozen. That frozen snapshot is the only thing evidence gets generated from.",
  },
];

export default function SimulationPage() {
  return (
    <MarketingShell>
      <PageHero
        title="Project Relay: the simulation behind every mission."
        description="A 50-minute deployment session that produces honest, rule-based evidence — not a quiz, not a personality test."
      />

      <section className="mkt-section border-t border-[var(--border-subtle)]">
        <Container>
          <div className="grid gap-0 border-t border-[var(--border-subtle)] sm:grid-cols-2 lg:grid-cols-4">
            {STAGES.map((stage, i) => (
              <Reveal key={stage.title} delay={0.03 * i}>
                <div className="border-b border-[var(--border-subtle)] py-6 sm:border-b-0 sm:border-r sm:px-5 sm:first:pl-0 sm:last:border-r-0 sm:last:pr-0">
                  <p className="text-[12px] text-[rgba(244,245,247,0.4)]">{String(i + 1).padStart(2, "0")}</p>
                  <h3 className="mt-2 text-[15px] text-[#F4F5F7]" style={{ fontWeight: 560 }}>
                    {stage.title}
                  </h3>
                  <p className="mt-2 text-[13.5px] leading-[1.55] text-[rgba(244,245,247,0.62)]">
                    {stage.body}
                  </p>
                </div>
              </Reveal>
            ))}
          </div>
        </Container>
      </section>

      <section className="mkt-section border-t border-[var(--border-subtle)]">
        <Container>
          <Reveal className="max-w-[640px]">
            <h2 className="section-heading flat-type">What the evidence is — and isn&apos;t.</h2>
            <p className="section-desc mt-5">
              Evidence findings are generated by simple rules over the recorded event timeline: did
              they run tests, did they iterate on files, did they message the customer, did they
              respond after the curveball. Every finding lists its confidence and its limitations —
              we don&apos;t pretend a rule-based read is a certified skills assessment.
            </p>
          </Reveal>
          <Reveal delay={0.06} className="mt-8">
            <ButtonLink href="/trust">Read our trust page</ButtonLink>
          </Reveal>
        </Container>
      </section>

      <FinalCTA />
    </MarketingShell>
  );
}
