import type { MicroSimContent } from "../micro-types";
import {
  MICRO_BI_ANALYST,
  MICRO_DATA_ANALYST,
  MICRO_SOLUTIONS_ENGINEER,
} from "./micro-data-analytics";
import {
  MICRO_BSA,
  MICRO_IMPLEMENTATION_CONSULTANT,
  MICRO_TSE,
} from "./micro-operations";
import {
  MICRO_DA_DUPLICATE_REVENUE,
  MICRO_DA_BROKEN_FUNNEL,
  MICRO_DA_REFUND_SPIKE,
  MICRO_DA_COHORT_DRIFT,
  MICRO_BI_FILTERED_FORECAST,
  MICRO_BI_NORTH_STAR,
  MICRO_BI_CURRENCY_CONFUSION,
  MICRO_BI_FISCAL_CUTOFF,
} from "./micro-data-analytics-2";
import {
  MICRO_SE_SSO_PROVISIONING,
  MICRO_SE_RATE_LIMIT,
  MICRO_SE_SECURITY_REVIEW,
  MICRO_SE_DATA_RESIDENCY,
  MICRO_IC_DUPLICATE_ACCOUNTS,
  MICRO_IC_APPROVAL_RULES,
  MICRO_IC_MIGRATION_CUTOVER,
  MICRO_IC_SCOPE_TRADEOFF,
} from "./micro-solutions-delivery-2";
import {
  MICRO_TSE_API_TIMEOUT,
  MICRO_TSE_PERMISSION_FAILURE,
  MICRO_TSE_DUPLICATE_WEBHOOKS,
  MICRO_TSE_ONE_CUSTOMER,
  MICRO_BSA_INVOICE_ROUTING,
  MICRO_BSA_ACCESS_PROVISIONING,
  MICRO_BSA_CRM_HANDOFF,
  MICRO_BSA_CHANGE_REQUEST,
} from "./micro-operations-2";

/**
 * Registry of published simulation content: 30 curated five-minute
 * simulations, five per Applied Technical Role. (The long-form content in
 * this directory remains unpublished and is not seeded to the catalog.)
 */
export const ALL_SIMULATIONS: MicroSimContent[] = [
  // Data Analyst
  MICRO_DATA_ANALYST,
  MICRO_DA_DUPLICATE_REVENUE,
  MICRO_DA_BROKEN_FUNNEL,
  MICRO_DA_REFUND_SPIKE,
  MICRO_DA_COHORT_DRIFT,
  // Business Intelligence Analyst
  MICRO_BI_ANALYST,
  MICRO_BI_FILTERED_FORECAST,
  MICRO_BI_NORTH_STAR,
  MICRO_BI_CURRENCY_CONFUSION,
  MICRO_BI_FISCAL_CUTOFF,
  // Solutions Engineer
  MICRO_SOLUTIONS_ENGINEER,
  MICRO_SE_SSO_PROVISIONING,
  MICRO_SE_RATE_LIMIT,
  MICRO_SE_SECURITY_REVIEW,
  MICRO_SE_DATA_RESIDENCY,
  // Implementation Consultant
  MICRO_IMPLEMENTATION_CONSULTANT,
  MICRO_IC_DUPLICATE_ACCOUNTS,
  MICRO_IC_APPROVAL_RULES,
  MICRO_IC_MIGRATION_CUTOVER,
  MICRO_IC_SCOPE_TRADEOFF,
  // Technical Support Engineer
  MICRO_TSE,
  MICRO_TSE_API_TIMEOUT,
  MICRO_TSE_PERMISSION_FAILURE,
  MICRO_TSE_DUPLICATE_WEBHOOKS,
  MICRO_TSE_ONE_CUSTOMER,
  // Business Systems Analyst
  MICRO_BSA,
  MICRO_BSA_INVOICE_ROUTING,
  MICRO_BSA_ACCESS_PROVISIONING,
  MICRO_BSA_CRM_HANDOFF,
  MICRO_BSA_CHANGE_REQUEST,
];

export const SIMULATION_BY_SLUG: Record<string, MicroSimContent> = Object.fromEntries(
  ALL_SIMULATIONS.map((s) => [s.slug, s])
);
