/**
 * Partial failure recovery test.
 * Simulates the message route's persistence flow with injected failures.
 * Verifies: no duplicates, no lost memory, correct assistance budgets.
 * Run: npx tsx scripts/test-partial-failure.ts
 */
import { buildStateFromMessages } from "../src/lib/simulations/conversation/state-builder";

// Mock persistence layer
interface MockMessage {
  id: string;
  sender: "candidate" | "stakeholder";
  stakeholderId?: string | null;
  body: string;
  created_at: string;
  clientMsgId?: string;
}

interface MockEvent {
  event_type: string;
  payload: Record<string, unknown>;
  created_at: string;
  clientEventId?: string;
}

class MockDB {
  messages: MockMessage[] = [];
  events: MockEvent[] = [];
  failMessages = false;
  failEvents = false;
  private msgSeq = 0;

  async insertMessage(input: {
    body: string;
    sender: "candidate" | "stakeholder";
    stakeholderId?: string;
    clientMsgId?: string;
  }): Promise<{ message: MockMessage; duplicate: boolean }> {
    if (this.failMessages) throw new Error("DB: message insert failed");
    // Idempotency check
    const existing = this.messages.find((m) => m.clientMsgId === input.clientMsgId);
    if (existing && input.clientMsgId) {
      return { message: existing, duplicate: true };
    }
    this.msgSeq++;
    const msg: MockMessage = {
      id: `msg_${this.msgSeq}`,
      sender: input.sender,
      stakeholderId: input.stakeholderId || null,
      body: input.body,
      created_at: new Date().toISOString(),
      clientMsgId: input.clientMsgId,
    };
    this.messages.push(msg);
    return { message: msg, duplicate: false };
  }

  async recordEvent(input: {
    eventType: string;
    payload: Record<string, unknown>;
    clientEventId?: string;
  }): Promise<void> {
    if (this.failEvents) throw new Error("DB: event record failed");
    const existing = this.events.find((e) => e.clientEventId === input.clientEventId);
    if (existing && input.clientEventId) return; // Idempotent
    this.events.push({
      event_type: input.eventType,
      payload: input.payload,
      created_at: new Date().toISOString(),
      clientEventId: input.clientEventId,
    });
  }
}

let failures = 0;
let passes = 0;

function check(name: string, fn: () => Promise<void>): Promise<void> {
  return fn().then(
    () => { passes++; console.log(`PASS ${name}`); },
    (err) => { failures++; console.error(`FAIL ${name}: ${err instanceof Error ? err.message : err}`); }
  );
}

function assertTrue(cond: boolean, msg: string): void {
  if (!cond) throw new Error(msg);
}

async function run() {
  // Scenario A: message succeeds, event fails, then retry
  await check("message OK + event fail → retry recovers", async () => {
    const db = new MockDB();
    const clientMsgId = "test_001";

    // Attempt 1: message succeeds, event fails
    const { message: candidateMsg } = await db.insertMessage({
      body: "Can I get a hint?",
      sender: "candidate",
      clientMsgId,
    });
    db.failEvents = true;
    try {
      await db.recordEvent({
        eventType: "message_received",
        payload: { stakeholderId: "maya", helpLevel: "hint" },
        clientEventId: `recv_${clientMsgId}`,
      });
      throw new Error("Should have failed");
    } catch (e) {
      assertTrue((e as Error).message.includes("event record failed"), "event should fail");
    }

    // Simulate coworker reply message (would be generated by LLM)
    const { message: replyMsg } = await db.insertMessage({
      body: "Think about idempotency keys.",
      sender: "stakeholder",
      stakeholderId: "maya",
      clientMsgId: `reply_${clientMsgId}`,
    });

    // Attempt 2 (retry): event now succeeds
    db.failEvents = false;
    await db.recordEvent({
      eventType: "message_received",
      payload: {
        stakeholderId: "maya",
        helpLevel: "hint",
        memoryUpdates: { topicsAddressed: ["idempotency"] },
      },
      clientEventId: `recv_${clientMsgId}`,
    });

    // Verify: rebuild state, check no duplicates and hint counted
    const state = buildStateFromMessages(
      "s1", "sc1", "v1",
      db.messages.map((m) => ({
        id: m.id,
        sender: m.sender,
        stakeholderId: m.stakeholderId,
        body: m.body,
        created_at: m.created_at,
      })),
      db.events.map((e) => ({
        event_type: e.event_type,
        payload: e.payload,
        created_at: e.created_at,
      }))
    );

    assertTrue(db.messages.length === 2, `messages: ${db.messages.length} (expected 2)`);
    assertTrue(state.helpGiven.length === 1, `hints: ${state.helpGiven.length} (expected 1)`);
    assertTrue(state.helpGiven[0].level === "hint", "hint level recorded");
  });

  // Scenario B: reverse — event succeeds, message fails, then retry
  await check("event OK + message fail → retry recovers", async () => {
    const db = new MockDB();
    const clientMsgId = "test_002";

    db.failMessages = true;
    try {
      await db.insertMessage({
        body: "What is the retry behavior?",
        sender: "candidate",
        clientMsgId,
      });
      throw new Error("Should have failed");
    } catch (e) {
      assertTrue((e as Error).message.includes("message insert failed"), "message should fail");
    }

    // Retry: message now succeeds
    db.failMessages = false;
    const { message, duplicate } = await db.insertMessage({
      body: "What is the retry behavior?",
      sender: "candidate",
      clientMsgId,
    });
    assertTrue(!duplicate, "should not be duplicate on first success");
    assertTrue(db.messages.length === 1, "exactly one message");

    // Duplicate retry (client retries after timeout)
    const retry = await db.insertMessage({
      body: "What is the retry behavior?",
      sender: "candidate",
      clientMsgId,
    });
    assertTrue(retry.duplicate, "retry should be idempotent");
    assertTrue(db.messages.length === 1, "still exactly one message");
  });

  // Scenario C: double event recording doesn't double-count hints
  await check("duplicate events don't double-count assistance", async () => {
    const db = new MockDB();
    await db.insertMessage({
      body: "Hint please",
      sender: "candidate",
      clientMsgId: "test_003",
    });
    await db.insertMessage({
      body: "Try idempotency.",
      sender: "stakeholder",
      stakeholderId: "maya",
      clientMsgId: "reply_test_003",
    });
    // Record same event twice (simulating retry)
    const eventPayload = {
      eventType: "message_received",
      payload: { stakeholderId: "maya", helpLevel: "hint" },
      clientEventId: "recv_test_003",
    };
    await db.recordEvent(eventPayload);
    await db.recordEvent(eventPayload); // Duplicate

    assertTrue(db.events.length === 1, `events: ${db.events.length} (expected 1)`);

    const state = buildStateFromMessages(
      "s1", "sc1", "v1",
      db.messages.map((m) => ({
        id: m.id, sender: m.sender, stakeholderId: m.stakeholderId,
        body: m.body, created_at: m.created_at,
      })),
      db.events.map((e) => ({
        event_type: e.event_type, payload: e.payload, created_at: e.created_at,
      }))
    );
    assertTrue(state.helpGiven.length === 1, `hints: ${state.helpGiven.length} (expected 1, not 2)`);
  });

  console.log(`\n${passes} passed, ${failures} failed`);
  if (failures > 0) process.exit(1);
}

run();
